local colors = require("horizon-extended.colors")

--TODO: standardize the variables so that if they are the same thing they are calling the same colors and styles
local M = {}
function M.setup()
	local config = require("horizon-extended.config")
	local options = config.options
	local theme = {
		config = options,
		colors = colors.setup(),
	}

	local c = theme.colors

	theme.highlights = {
		Character = { link = "string" }, -- Single characters like 'c' or '\n'
		Comment = { fg = c.mg1, style = options.styles.comments }, -- comments
		Conditional = { fg = c.accent, style = options.styles.conditionals },
		Constant = { fg = c.accent }, -- (preferred) any constant
		Cursor = { fg = c.bg0, bg = c.fg1 },
		CursorColumn = { link = "CursorLine" },
		CursorLine = { bg = c.mg3 },
		Delimiter = { fg = c.fg0, style = options.styles.delimiters }, -- punctuation
		DiffAdd = { bg = c.diffadd },
		DiffChange = { bg = c.diffchange },
		DiffText = { bg = c.difftext },
		DiffDelete = { bg = c.diffdelete },
		Directory = { fg = c.warning },
		EndOfBuffer = { fg = options.show_end_of_buffer and c.mg1 or c.bg0 },
		ErrorText = { sp = c.error, undercurl = options.undercurl },
		ErrorMsg = { fg = c.error },
		Folded = { fg = c.info, bg = c.bg2 },
		Function = { fg = c.info }, -- (preferred) function names
		HintText = { fg = c.success },
		Identifier = { fg = c.error }, -- (preferred) any variable name
		LineNr = { fg = c.mg2 },
		MatchParen = { fg = c.warning, bg = c.mg0, bold = true },
		Normal = { fg = c.fg0, bg = options.transparent and c.none or c.bg0 }, -- Normal text
		NormalFloat = { fg = c.fg0, bg = options.transparent and c.none or c.bg0 }, -- Normal text in a floating window
		FloatBorder = { fg = c.border },
		FloatTitle = { fg = c.error },
		NormalNC = { fg = c.fg0, bg = options.transparent and c.none or c.bg0 }, -- Normal text in a non-current window
		ModeMsg = { fg = c.fg2 },
		MoreMsg = { fg = c.heading },
		CurSearch = { link = "IncSearch" },
		IncSearch = { fg = c.bg0, bg = c.accent },
		PreProc = { fg = c.heading },
		QuickFixLine = { bg = c.bg1, bold = true, undercurl = options.undercurl }, -- Current |quickfix| item in the quickfix window. Combined with |hl-CursorLine| when the cursor is there.
		Repeat = { fg = c.accent, style = options.styles.loops },
		Search = { fg = c.bg0, bg = c.warning },
		SignatureMarkText = { fg = c.heading },
		SignatureMarkLine = { bg = c.markline },
		SignColumn = { bg = options.transparent and c.none or c.bg0 },
		SignColumnSB = { bg = c.bg0, fg = c.bg1 },
		Special = { fg = c.accent }, -- special items
		SpellBad = { sp = c.error, undercurl = options.undercurl },
		SpellCap = { sp = c.info, undercurl = options.undercurl }, -- Word that should start with a capital. |spell| Combined with the highlighting used otherwise.
		SpellLocal = { sp = c.heading, undercurl = options.undercurl }, -- Word that is recognized by the spellchecker as one that is used in another region. |spell| Combined with the highlighting used otherwise.
		SpellRare = { sp = c.success, undercurl = options.undercurl }, -- Word that is recognized by the spellchecker as one that is hardly ever used.  |spell| Combined with the highlighting used otherwise.
		Statement = { fg = c.heading, italic = options.enable_italics }, -- (preferred) any statment (if, for, case, etc.)
		StatusLine = { fg = c.fg0, bg = options.transparent and c.none or c.bg0 }, -- status line of current window
		StatusLineNC = { fg = c.fg2 }, -- status lines of not-current windows Note: if this is equal to "StatusLine" Vim will use "^^^" in the status line of the current window.
		String = { fg = c.success, style = options.styles.strings }, -- Strings
		Tag = { fg = c.error },
		TabLine = { fg = c.fg2 }, -- tab pages line, not active tab page label
		TabLineFill = { bg = c.bg0 }, -- tab pages line, where there are no labels
		TabLineSel = { fg = c.bg0, bg = c.info }, -- tab pages line, active tab page label
		Title = { fg = c.info },
		Type = { fg = c.warning, style = options.styles.types },
		Question = { fg = c.info },
		Removed = { fg = c.error },
		VertSplit = { fg = c.fg1 },
		Visual = { bg = c.mg2 },
		VisualNOS = { bg = c.bg1 }, -- Visual mode selection when vim is "Not Owning the Selection".
		WarningMsg = { fg = c.error },
		WarningText = { sp = c.warning, undercurl = true },
		Whitespace = { fg = c.mg3 }, -- "nbsp", "space", "tab" and "trail" in 'listchars'
		WildMenu = { bg = c.bg1 }, -- current match in 'wildmenu' completion
		WinSeparator = { fg = c.mg2 }, -- the column separating vertically split windows
		lCursor = { fg = c.bg0, bg = c.fg0 }, -- the character under the cursor when |language-mapping| is used (see 'guicursor')

		-- Diagnostic
		RedSign = { fg = c.error },
		YellowSign = { fg = c.warning },
		GreenSign = { fg = c.success },
		BlueSign = { fg = c.info },
		VirtualTextWarning = { fg = c.warning },
		VirtualTextError = { fg = c.error },
		VirtualTextInfo = { fg = c.info },
		VirtualTextHint = { fg = c.success },
		ErrorFloat = { fg = c.error, bg = c.bg1 },
		WarningFloat = { fg = c.warning, bg = c.bg1 },
		InfoFloat = { fg = c.info, bg = c.bg1 },
		HintFloat = { fg = c.success, bg = c.bg1 },
		--[[ WinBarNC                   = { fg = c.mg0 }, ]]
		DiagnosticFloatingError = { link = "ErrorFloat" },
		DiagnosticFloatingWarn = { link = "WarningFloat" },
		DiagnosticFloatingInfo = { link = "InfoFloat" },
		DiagnosticFloatingHint = { link = "HintFloat" },
		DiagnosticError = { fg = c.error },
		DiagnosticWarn = { fg = c.warning },
		DiagnosticInfo = { fg = c.info },
		DiagnosticHint = { fg = c.success },
		DiagnosticVirtualTextError = { link = "VirtualTextError" },
		DiagnosticVirtualTextWarn = { link = "VirtualTextWarning" },
		DiagnosticVirtualTextInfo = { link = "VirtualTextInfo" },
		DiagnosticVirtualTextHint = { link = "VirtualTextHint" },
		DiagnosticUnderlineError = { link = "ErrorText" },
		DiagnosticUnderlineWarn = { link = "WarningText" },
		DiagnosticUnderlineInfo = { link = "InfoText" },
		DiagnosticUnderlineHint = { link = "HintText" },
		DiagnosticSignError = { link = "RedSign" },
		DiagnosticSignWarn = { link = "YellowSign" },
		DiagnosticSignHiblue = { link = "BlueSign" },
		DiagnosticSignInfo = { link = "GreenSign" },
		-- These groups are for the native LSP client. Some other LSP clients may
		-- use these groups, or use their own. Consult your LSP client's
		-- documentation.
		LspDiagnosticsFloatingError = { link = "DiagnosticFloatingError" },
		LspDiagnosticsFloatingWarning = { link = "DiagnosticFloatingWarn" },
		LspDiagnosticsFloatingInformation = { link = "DiagnosticFloatingInfo" },
		LspDiagnosticsFloatingHint = { link = "DiagnosticFloatingHint" },
		LspDiagnosticsDefaultError = { link = "DiagnosticError" },
		LspDiagnosticsDefaultWarning = { link = "DiagnosticWarn" },
		LspDiagnosticsDefaultInformation = { link = "DiagnosticInfo" },
		LspDiagnosticsDefaultHint = { link = "DiagnosticHint" },
		LspDiagnosticsVirtualTextError = { link = "DiagnosticVirtualTextError" },
		LspDiagnosticsVirtualTextWarning = { link = "DiagnosticVirtualTextWarn" },
		LspDiagnosticsVirtualTextInformation = { link = "DiagnosticVirtualTextInfo" },
		LspDiagnosticsVirtualTextHint = { link = "DiagnosticVirtualTextHint" },
		LspDiagnosticsUnderlineError = { link = "DiagnosticUnderlineError" },
		LspDiagnosticsUnderlineWarning = { link = "DiagnosticUnderlineWarn" },
		LspDiagnosticsUnderlineInformation = { link = "DiagnosticUnderlineInfo" },
		LspDiagnosticsUnderlineHint = { link = "DiagnosticUnderlineHint" },
		LspDiagnosticsSignError = { link = "DiagnosticSignError" },
		LspDiagnosticsSignWarning = { link = "DiagnosticSignWarn" },
		LspDiagnosticsSignInformation = { link = "DiagnosticSignInfo" },
		LspDiagnosticsSignHint = { link = "DiagnosticSignHint" },
		LspReferenceText = { link = "CurrentWord" },
		LspReferenceRead = { link = "CurrentWord" },
		LspReferenceWrite = { link = "CurrentWord" },
		LspCodeLens = { link = "VirtualTextInfo" },
		LspCodeLensSeparator = { link = "VirtualTextHint" },
		LspSignatureActiveParameter = { link = "Search" },
		TermCursor = { link = "Cursor" },
		healthError = { fg = c.error },
		healthSuccess = { fg = c.success },
		healthWarning = { fg = c.warning },
		ALEErrorSign = { link = "ErrorMsg" },
		ALEWarningSign = { link = "WarningMsg" },

		-- These highlight Groups are for Tree-sitter
		TSAnnotation = { fg = c.heading },
		TSAttribute = { fg = c.heading },
		TSBoolean = { fg = c.accent, style = options.styles.booleans },
		TSCharacter = { fg = c.info },
		TSComment = { link = "Comment" },
		TSConditional = { link = "Conditional" },
		TSConstBuiltin = { fg = c.info, italic = true },
		TSConstMacro = { fg = c.info, italic = true },
		TSConstant = { fg = c.fg0 },
		TSConstructor = { fg = c.success, bold = true },
		TSException = { fg = c.error },
		TSField = { fg = c.success },
		TSFloat = { fg = c.heading },
		TSFuncBuiltin = { fg = c.success, bold = true },
		TSFuncMacro = { fg = c.success, bold = true },
		TSFunction = { fg = c.success, bold = true },
		TSInclude = { fg = c.error },
		TSKeyword = { fg = c.error },
		TSKeywordFunction = { fg = c.error },
		TSKeywordOperator = { fg = c.accent },
		TSLabel = { fg = c.accent },
		TSMethod = { fg = c.success, bold = true },
		TSNamespace = { fg = c.warning, italic = true },
		TSNone = { fg = c.fg0 },
		TSNumber = { fg = c.heading },
		TSOperator = { fg = c.accent, style = options.styles.operators },
		TSParameter = { fg = c.error },
		TSParameterReference = { fg = c.fg0 },
		TSProperty = { fg = c.error, style = options.styles.properties },
		TSPunctBracket = { fg = c.fg0 },
		TSPunctDelimiter = { fg = c.mg1 },
		TSPunctSpecial = { fg = c.info },
		TSRepeat = { fg = c.error },
		TSStorageClass = { fg = c.accent },
		TSString = { fg = c.info },
		TSStringEscape = { fg = c.success },
		TSStringRegex = { fg = c.success },
		TSSymbol = { fg = c.fg0 },
		TSTag = { fg = c.accent },
		TSTagDelimiter = { fg = c.success },
		TSText = { fg = c.success },
		TSStrike = { fg = c.mg1 },
		TSMath = { fg = c.info },
		TSType = { fg = c.warning, style = options.styles.types },
		TSTypeBuiltin = { fg = c.warning, italic = true },
		TSURI = { link = "markdownUrl" },
		TSVariable = { fg = c.fg0 },
		TSVariableBuiltin = { fg = c.warning, italic = true },

		-- Identifiers
		["@annotation"] = { link = "PreProc" },
		["@attribute"] = { link = "PreProc" },
		["@boolean"] = { link = "TSBoolean" },
		["@character"] = { link = "Character" },
		["@character.printf"] = { link = "SpecialChar" },
		["@character.special"] = { link = "SpecialChar" },
		["@comment"] = { link = "Comment" },
		["@comment.error"] = { fg = c.error },
		["@comment.hint"] = { fg = c.success },
		["@comment.info"] = { fg = c.info },
		["@comment.note"] = { fg = c.hint },
		["@comment.todo"] = { fg = c.heading },
		["@comment.warning"] = { fg = c.accent },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Special" },
		["@constant.macro"] = { link = "Define" },
		["@constructor"] = { fg = c.heading }, -- For constructor calls and definitions: `= { }` in Lua, and Java constructors.
		["@constructor.tsx"] = { fg = c.info },
		["@diff.delta"] = { link = "DiffChange" },
		["@diff.minus"] = { link = "DiffDelete" },
		["@diff.plus"] = { link = "DiffAdd" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { link = "Special" },
		["@function.call"] = { link = "@function" },
		["@function.macro"] = { link = "Macro" },
		["@function.method"] = { link = "Function" },
		["@function.method.call"] = { link = "@function.method" },
		["@keyword"] = { fg = c.heading, style = options.styles.keywords }, -- For keywords that don't fall in previous categories.
		["@keyword.conditional"] = { link = "Conditional" },
		["@keyword.coroutine"] = { link = "@keyword" },
		["@keyword.debug"] = { link = "Debug" },
		["@keyword.directive"] = { link = "PreProc" },
		["@keyword.directive.define"] = { link = "Define" },
		["@keyword.exception"] = { link = "Exception" },
		["@keyword.function"] = { fg = c.heading, style = options.styles.functions }, -- For keywords used to define a function.
		["@keyword.import"] = { link = "Include" },
		["@keyword.operator"] = { fg = c.heading, style = options.styles.operators },
		["@keyword.repeat"] = { link = "Repeat" },
		["@keyword.return"] = { link = "@keyword" },
		["@keyword.storage"] = { link = "StorageClass" },
		["@label"] = { fg = c.info }, -- For labels: `label:` in C and `:label:` in Lua.
		["@markup"] = { link = "@none" },
		["@markup.emphasis"] = { italic = true },
		["@markup.environment"] = { link = "Macro" },
		["@markup.environment.name"] = { link = "Type" },
		["@markup.heading"] = { link = "Title" },
		["@markup.italic"] = { italic = true },
		["@markup.link"] = { fg = c.info },
		["@markup.link.label"] = { link = "SpecialChar" },
		["@markup.link.label.symbol"] = { link = "Identifier" },
		["@markup.link.url"] = { link = "Underlined" },
		["@markup.list"] = { fg = c.info }, -- For special punctutation that does not fall in the categories before.
		["@markup.list.checked"] = { fg = c.success }, -- For brackets and parens.
		["@markup.list.unchecked"] = { fg = c.info }, -- For brackets and parens.
		["@markup.math"] = { link = "Special" },
		["@markup.raw"] = { link = "String" },
		["@markup.raw.markdown_inline"] = { fg = c.info },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.strong"] = { bold = true },
		["@markup.underline"] = { underline = true },
		["@module"] = { link = "Include" },
		["@module.builtin"] = { fg = c.error }, -- Variable names that are defined by the languages, like `this` or `self`.
		["@namespace.builtin"] = { link = "@variable.builtin" },
		["@none"] = {},
		["@number"] = { link = "Number" },
		["@number.float"] = { link = "Float" },
		["@operator"] = { fg = c.info, style = options.styles.operators }, -- For any operator: `+`, but also `->` and `*` in C.
		["@property"] = { fg = c.success, style = options.styles.properties },
		["@punctuation.bracket"] = { fg = c.fg2 }, -- For brackets and parens.
		["@punctuation.delimiter"] = { fg = c.info }, -- For delimiters ie: `.`
		["@punctuation.special"] = { fg = c.info }, -- For special symbols (e.g. `{}` in string interpolation)
		["@string"] = { link = "String" },
		["@string.documentation"] = { fg = c.success },
		["@string.escape"] = { fg = c.error }, -- For escape characters within a string.
		["@string.regexp"] = { fg = c.info }, -- For regexes.
		["@tag"] = { fg = c.error },
		["@tag.builtin"] = { fg = c.error },
		["@tag.delimiter"] = { fg = c.error },
		["@tag.attribute"] = { fg = c.accent, italic = options.enable_italics },
		["@tag.delimiter.tsx"] = { fg = c.info },
		["@tag.tsx"] = { fg = c.error },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = c.heading },
		["@type.definition"] = { link = "Typedef" },
		["@type.qualifier"] = { link = "@keyword" },
		["@variable"] = { fg = c.error, style = options.styles.variables }, -- Any variable name that does not have another highlight.
		["@variable.builtin"] = { fg = c.error }, -- Variable names that are defined by the languages, like `this` or `self`.
		["@variable.member"] = { fg = c.accent }, -- For fields.
		["@variable.parameter"] = { fg = c.warning }, -- For parameters of a function.
		["@variable.parameter.builtin"] = { fg = c.warning }, -- For builtin parameters of a function, e.g. "..." or Smali's p[1-99]
		["@text.reference"] = { fg = c.heading },
		["@text.todo.unchecked"] = { fg = c.info }, -- For brackets and parens.
		["@text.todo.checked"] = { fg = c.success }, -- For brackets and parens.
		["@text.warning"] = { fg = c.bg, bg = c.warning },
		["@text.danger"] = { fg = c.fg0, bg = c.error },
		["@text.diff.add"] = { link = "DiffAdd" },
		["@text.diff.delete"] = { link = "DiffDelete" },
		["@namespace"] = { link = "Include" },

		-- LSP Semantic Token Groups
		["@lsp.type.comment"] = { link = "TSComment" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "TSConstructor" },
		["@lsp.type.interface"] = { fg = c.info },
		["@lsp.type.keyword"] = { link = "TSKeyword" },
		["@lsp.type.modifier"] = { fg = c.error },
		["@lsp.type.namespace"] = { link = "TSNameSpace" },
		["@lsp.type.parameter"] = { link = "TSParameter" },
		["@lsp.type.property"] = { link = "TSProperty" },
		["@lsp.type.variable"] = { fg = c.error },
		["@lsp.mod.readonly"] = { fg = c.warning },
		["@lsp.typemod.function"] = { fg = c.info },
		["@lsp.typemod.macro.defaultLibrary"] = { link = "TSFuncBuiltin" },
		["@lsp.typemod.method.defaultLibrary"] = { link = "TSFuncBuiltin" },
		["@lsp.typemod.operator.injected"] = { link = "TSOperator" },
		["@lsp.typemod.string.injected"] = { link = "@string" },
		["@lsp.typemod.type.defaultLibrary"] = { fg = c.info },
		["@lsp.typemod.variable.defaultLibrary"] = { link = "TSVariableBuiltin" },
		["@lsp.typemod.variable.injected"] = { link = "TSVariable" },
		["@lsp.typemod.class.declaration"] = { fg = c.warning },

		-- ts-rainbow
		rainbowcol1 = { fg = c.error },
		rainbowcol2 = { fg = c.accent },
		rainbowcol3 = { fg = c.accent },
		rainbowcol4 = { fg = c.warning },
		rainbowcol5 = { fg = c.success },
		rainbowcol6 = { fg = c.info },
		rainbowcol7 = { fg = c.heading },

		-- PLUGINS
		-- Dashboard
		DashboardHeader = { fg = c.dashboard },
		DashboardFooter = { fg = c.dashboard },
		DashboardShortCut = { fg = c.purple },
		DashboardProjectTitle = { fg = c.heading },
		DashboardProjectIcon = { fg = c.dashboard },
		DashboardFiles = { fg = c.fg0 },
		DashboardMruTitle = { fg = c.heading },

		-- Indent Blank Line
		IblIdent = { fg = c.error },
		IblScope = { fg = c.error },
		RainbowRed = { blend = 0, fg = c.error },
		RainbowYellow = { blend = 0, fg = c.warning },
		RainbowBlue = { blend = 0, fg = c.info },
		RainbowOrange = { blend = 0, fg = c.accent },
		RainbowGreen = { blend = 0, fg = c.success },
		RainbowViolet = { blend = 0, fg = c.heading },
		RainbowCyan = { blend = 0, fg = c.info },

		-- Telescope
		TelescopeMatching = { fg = c.accent, bold = true },
		TelescopeBorder = { fg = c.border },
		TelescopePromptPrefix = { fg = c.accent },

		-- Neotree
		NeoTreeDirectoryName = { fg = c.warning },
		NeoTreeDirectoryIcon = { fg = c.warning },
		NeoTreeSymbolicLinkTarget = { fg = c.accent },
		NeoTreeGitAdded = { fg = c.success },
		NeoTreeGitConflict = { fg = c.error },
		NeoTreeGitDeleted = { fg = c.error },
		NeoTreeGitModified = { fg = c.warning },
		NeoTreeGitUnstaged = { fg = c.error },
		NeoTreeGitUntracked = { fg = c.info },
		NeoTreeGitStaged = { fg = c.success },
		NeoTreeFloatBorder = { fg = c.border },
		NeoTreeFloatTitle = { fg = c.heading },
		NeoTreeFileNameOpened = { fg = c.info },

		-- WhichKey
		WhichKey = { fg = c.accent },
		WhichKeyGroup = { fg = c.heading },
		WhichKeyDesc = { fg = c.fg0 },
		WhichKeySeparator = { fg = c.success },
		WhichKeyFloat = { fg = c.heading },
		WhichKeyBorder = { fg = c.border },

		-- Notify
		NotifyBackground = { bg = c.bg0 },
		NotifyERRORBorder = { fg = c.error },
		NotifyWARNBorder = { fg = c.warning },
		NotifyINFOBorder = { fg = c.success },
		NotifyDEBUGBorder = { fg = c.info },
		NotifyTRACEBorder = { fg = c.accent },
		NotifyERRORIcon = { fg = c.error },
		NotifyWARNIcon = { fg = c.warning },
		NotifyINFOIcon = { fg = c.success },
		NotifyDEBUGIcon = { fg = c.info },
		NotifyTRACEIcon = { fg = c.accent },
		NotifyERRORTitle = { fg = c.error },
		NotifyWARNTitle = { fg = c.warning },
		NotifyINFOTitle = { fg = c.success },
		NotifyDEBUGTitle = { fg = c.info },
		NotifyTRACETitle = { fg = c.accent },

		-- Noice
		NoiceCmdlineIcon = { fg = c.accent },
		NoiceCmdlineIconHelp = { fg = c.success },
		NoiceCmdlineIconLua = { fg = c.info },
		NoiceCmdlinePopupBorder = { fg = c.border },
		-- NoiceAttr10 = { fg = c.purple },
		NoiceCompletionItemKindDefault = { fg = c.fg2, bg = c.none },
		NoiceCompletionItemKindKeyword = { fg = c.accent, bg = c.none },
		NoiceCompletionItemKindVariable = { fg = c.accent, bg = c.none },
		NoiceCompletionItemKindConstant = { fg = c.accent, bg = c.none },
		NoiceCompletionItemKindReference = { fg = c.accent, bg = c.none },
		NoiceCompletionItemKindValue = { fg = c.accent, bg = c.none },
		NoiceCompletionItemKindFunction = { fg = c.info, bg = c.none },
		NoiceCompletionItemKindMethod = { fg = c.info, bg = c.none },
		NoiceCompletionItemKindConstructor = { fg = c.info, bg = c.none },
		NoiceCompletionItemKindClass = { fg = c.warning, bg = c.none },
		NoiceCompletionItemKindInterface = { fg = c.warning, bg = c.none },
		NoiceCompletionItemKindStruct = { fg = c.warning, bg = c.none },
		NoiceCompletionItemKindEvent = { fg = c.warning, bg = c.none },
		NoiceCompletionItemKindEnum = { fg = c.warning, bg = c.none },
		NoiceCompletionItemKindUnit = { fg = c.warning, bg = c.none },
		NoiceCompletionItemKindModule = { fg = c.heading, bg = c.none },
		NoiceCompletionItemKindProperty = { fg = c.success, bg = c.none },
		NoiceCompletionItemKindField = { fg = c.success, bg = c.none },
		NoiceCompletionItemKindTypeParameter = { fg = c.success, bg = c.none },
		NoiceCompletionItemKindEnumMember = { fg = c.success, bg = c.none },
		NoiceCompletionItemKindOperator = { fg = c.success, bg = c.none },
		NoiceCompletionItemKindSnippet = { fg = c.bg0, bg = c.none },

		-- Undotree
		UndotreeTimeStamp = { fg = c.heading },

		-- -- Bufferline
		-- BufferLineFill = { bg = c.bg4 },
		-- BufferLineBackground = { bg = c.bg2 },
		-- BufferLineCloseButton = { fg = c.mg0, bg = c.bg2 },
		-- BufferLineCloseButtonSelected = { fg = c.fg0, bg = c.bg0 },
		-- BufferLineCloseButtonVisible = { fg = c.fg0, bg = c.bg0 },
		-- BufferLineBufferVisible = { fg = c.mg1, bg = c.bg0 },
		-- BufferLineBufferSelected = { bg = c.bg0 },
		-- BufferLineNumbers = { fg = c.mg0, bg = c.bg2 },
		-- BufferLineNumbersVisible = { fg = c.mg1, bg = c.bg0 },
		-- BufferLineNumbersSelected = { bg = c.bg0 },
		-- BufferLineHint = { fg = c.info, bg = c.bg2 },
		-- BufferLineHintSelected = { fg = c.info, bg = c.bg0 },
		-- BufferLineHintVisible = { fg = c.info, bg = c.bg0 },
		-- BufferLineInfo = { fg = c.success, bg = c.bg2 },
		-- BufferLineInfoSelected = { fg = c.success, bg = c.bg0 },
		-- BufferLineInfoVisible = { fg = c.success, bg = c.bg0 },
		-- BufferLineWarning = { fg = c.warning, bg = c.bg2 },
		-- BufferLineWarningSelected = { fg = c.warning, bg = c.bg0 },
		-- BufferLineWarningVisible = { fg = c.warning, bg = c.bg0 },
		-- BufferLineError = { fg = c.error, bg = c.bg2 },
		-- BufferLineErrorSelected = { fg = c.error, bg = c.bg0 },
		-- BufferLineErrorVisible = { fg = c.error, bg = c.bg0 },
		-- BufferLineSeparator = { fg = c.bg4, bg = c.bg2 },
		-- BufferLineSeparatorSelected = { fg = c.bg4, bg = c.bg0 },
		-- BufferLineSeparatorVisible = { fg = c.bg4, bg = c.bg0 },
		-- BufferLineNeoTree = { fg = c.fg0, bg = c.bg2 },
		-- BufferLineModified = { fg = c.accent, bg = c.bg2 },
		-- BufferLineModifiedVisible = { fg = c.accent, bg = c.bg0 },
		-- BufferLineModifiedSelected = { fg = c.accent, bg = c.bg0 },

		-- diff
		diffAdded = { fg = c.success },
		diffRemoved = { fg = c.error },
		diffChanged = { fg = c.warning },
		diffOldFile = { fg = c.warning },
		diffNewFile = { fg = c.accent },
		diffFile = { fg = c.info },
		diffLine = { fg = c.mg0 },
		diffIndexLine = { fg = c.accent },

		-- GitSigns
		GitSignsAdd = { link = "GreenSign" }, -- diff mode: Added line |diff.txt|
		GitSignsChange = { link = "YellowSign" }, -- diff mode: Changed line |diff.txt|
		GitSignsDelete = { link = "RedSign" }, -- diff mode: Deleted line |diff.txt|
		GitSignsAddNr = { fg = c.success },
		GitSignsChangeNr = { fg = c.warning },
		GitSignsDeleteNr = { fg = c.error },
		GitSignsAddLn = { link = "diffAdded" },
		GitSignsDeleteLn = { link = "diffRemoved" },
		GitSignsCurrentLineBlame = { fg = c.mg0 },

		-- Cmp
		CmpDocumentation = { fg = c.fg1, bg = options.transparent and c.none or c.bg1 },
		CmpDocumentationBorder = { fg = c.border, bg = options.transparent and c.none or c.bg0 },
		CmpItemKindDefault = { fg = c.fg1, bg = c.none },
		CmpItemAbbrMatch = { fg = c.accent, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = c.accent, bold = true },
		CmpItemAbbr = { fg = c.fg0 },
		CmpItemAbbrDeprecated = { fg = c.mg0 },
		CmpItemMenu = { fg = c.fg0 },
		CmpItemKind = { fg = c.heading },
		CmpItemKindText = { fg = c.fg0 },
		CmpItemKindMethod = { fg = c.success },
		CmpItemKindFunction = { fg = c.accent },
		CmpItemKindConstructor = { fg = c.success },
		CmpItemKindField = { fg = c.success },
		CmpItemKindVariable = { fg = c.error },
		CmpItemKindClass = { fg = c.heading },
		CmpItemKindInterface = { fg = c.heading },
		CmpItemKindModule = { fg = c.heading },
		CmpItemKindProperty = { fg = c.error },
		CmpItemKindUnit = { fg = c.accent },
		CmpItemKindValue = { fg = c.accent },
		CmpItemKindEnum = { fg = c.heading },
		CmpItemKindKeyword = { fg = c.error },
		CmpItemKindSnippet = { fg = c.info },
		CmpItemKindColor = { fg = c.info },
		CmpItemKindFile = { fg = c.info },
		CmpItemKindReference = { fg = c.info },
		CmpItemKindFolder = { fg = c.info },
		CmpItemKindEnumMember = { fg = c.accent },
		CmpItemKindConstant = { fg = c.info },
		CmpItemKindStruct = { fg = c.heading },
		CmpItemKindEvent = { fg = c.warning },
		CmpItemKindOperator = { fg = c.warning },
		CmpItemKindTypeParameter = { fg = c.heading },
		NavicIconsFile = { fg = c.fg0 },
		NavicIconsModule = { fg = c.heading },
		NavicIconsNamespace = { fg = c.fg0 },
		NavicIconsPackage = { fg = c.fg0 },
		NavicIconsClass = { fg = c.warning },
		NavicIconsMethod = { fg = c.info },
		NavicIconsProperty = { fg = c.success },
		NavicIconsField = { fg = c.success },
		NavicIconsConstructor = { fg = c.warning },
		NavicIconsEnum = { fg = c.warning },
		NavicIconsInterface = { fg = c.warning },
		NavicIconsFunction = { fg = c.info },
		NavicIconsVariable = { fg = c.accent },
		NavicIconsConstant = { fg = c.accent },
		NavicIconsString = { fg = c.success },
		NavicIconsNumber = { fg = c.warning },
		NavicIconsBoolean = { fg = c.warning },
		NavicIconsArray = { fg = c.warning },
		NavicIconsObject = { fg = c.warning },
		NavicIconsKey = { fg = c.accent },
		NavicIconsKeyword = { fg = c.accent },
		NavicIconsNull = { fg = c.warning },
		NavicIconsEnumMember = { fg = c.success },
		NavicIconsStruct = { fg = c.warning },
		NavicIconsEvent = { fg = c.warning },
		NavicIconsOperator = { fg = c.fg0 },
		NavicIconsTypeParameter = { fg = c.success },
		NavicText = { fg = c.fg0 },
		NavicSeparator = { fg = c.fg0 },

		-- LANGUAGES

		-- CSS
		cssAttrComma = { fg = c.fg0 },
		cssBraces = { fg = c.fg0 },
		cssTagName = { fg = c.error, italic = options.enable_italics },
		cssClassNameDot = { fg = c.accent },
		cssClassName = { fg = c.accent, italic = options.enable_italics },
		cssFunctionName = { fg = c.info },
		cssAttr = { fg = c.warning },
		cssProp = { fg = c.warning },
		cssCommonAttr = { fg = c.error },
		cssPseudoClassId = { fg = c.info },
		cssPseudoClassFn = { fg = c.success },
		cssPseudoClass = { fg = c.accent },
		cssImportant = { fg = c.error, italic = options.enable_italics },
		cssSelectorOp = { fg = c.warning },
		cssSelectorOp2 = { fg = c.warning },
		cssColor = { fg = c.fg0 },
		cssAttributeSelector = { fg = c.info },
		cssUnitDecorators = { fg = c.fg0 },
		cssValueLength = { fg = c.fg0 },
		cssValueInteger = { fg = c.fg0 },
		cssValueNumber = { fg = c.fg0 },
		cssValueAngle = { fg = c.fg0 },
		cssValueTime = { fg = c.fg0 },
		cssValueFrequency = { fg = c.fg0 },
		cssVendor = { fg = c.mg0 },
		cssNoise = { fg = c.mg0 },
		cssCustomProp = { fg = c.error },

		-- HTML

		-- JavaScript
		javaScriptNull = { fg = c.info },
		javaScriptIdentifier = { fg = c.warning },
		javaScriptParens = { fg = c.fg0 },
		javaScriptBraces = { fg = c.fg0 },
		javaScriptGlobal = { fg = c.heading },
		javaScriptMessage = { fg = c.heading },
		javaScriptFunction = { fg = c.error, italic = options.enable_italics },
		javaScriptOperator = { fg = c.warning },
		javaScriptMember = { fg = c.info },

		-- Python
		pythonBuiltin = { fg = c.heading },
		pythonExceptions = { fg = c.heading },
		pythonDecoratorName = { fg = c.info },
		["@function.builtin.python"] = { link = "Function" },

		-- Rust
		rustStructure = { fg = c.warning },
		rustIdentifier = { fg = c.accent },
		rustModPath = { fg = c.warning },
		rustModPathSep = { fg = c.fg0 },
		rustSelf = { fg = c.info },
		rustSuper = { fg = c.info },
		rustDeriveTrait = { fg = c.accent, italic = options.enable_italics },
		rustEnumVariant = { fg = c.accent },
		rustMacroVariable = { fg = c.info },
		rustAssert = { fg = c.info },
		rustPanic = { fg = c.info },
		rustPubScopeCrate = { fg = c.accent, italic = options.enable_italics },

		-- MarkDown
		markdownH1 = { fg = c.error, bold = true },
		markdownH2 = { fg = c.warning, bold = true },
		markdownH3 = { fg = c.heading, bold = true },
		markdownH4 = { fg = c.success, bold = true },
		markdownH5 = { fg = c.info, bold = true },
		markdownH6 = { fg = c.accent, bold = true },
		markdownUrl = { fg = c.info, underline = true },
		markdownItalic = { italic = true },
		markdownBold = { bold = true },
		markdownItalicDelimiter = { fg = c.mg0, italic = true },
		markdownCode = { fg = c.success },
		markdownCodeBlock = { fg = c.info },
		markdownCodeDelimiter = { fg = c.info },
		markdownBlockquote = { fg = c.fg2 },
		markdownListMarker = { fg = c.error },
		markdownOrderedListMarker = { fg = c.error },
		markdownRule = { fg = c.accent },
		markdownHeadingRule = { fg = c.mg0 },
		markdownUrlDelimiter = { fg = c.mg0 },
		markdownLinkDelimiter = { fg = c.mg0 },
		markdownLinkTextDelimiter = { fg = c.mg0 },
		markdownHeadingDelimiter = { fg = c.mg0 },
		markdownLinkText = { fg = c.accent },
		markdownUrlTitleDelimiter = { fg = c.mg0 },
		markdownIdDeclaration = { link = "markdownLinkText" },
		markdownBoldDelimiter = { fg = c.mg0 },
		markdownId = { fg = c.heading },
		["@punctuation.special.markdown"] = { fg = c.accent, bold = true },
		["@text.literal.markdown_inline"] = { bg = c.bg0, fg = c.info },
		["@markup.heading.1.markdown"] = { link = "markdownH1" },
		["@markup.heading.2.markdown"] = { link = "markdownH2" },
		["@markup.heading.3.markdown"] = { link = "markdownH3" },
		["@markup.heading.4.markdown"] = { link = "markdownH4" },
		["@markup.heading.5.markdown"] = { link = "markdownH5" },
		["@markup.heading.6.markdown"] = { link = "markdownH6" },
		["@markup.heading.1.marker.markdown"] = { link = "markdownH1" },
		["@markup.heading.2.marker.markdown"] = { link = "markdownH2" },
		["@markup.heading.3.marker.markdown"] = { link = "markdownH3" },
		["@markup.heading.4.marker.markdown"] = { link = "markdownH4" },
		["@markup.heading.5.marker.markdown"] = { link = "markdownH5" },
		["@markup.heading.6.marker.markdown"] = { link = "markdownH6" },
		["@markup.list.markdown"] = { link = "markdownListMarker" },
		["@markup.quote.markdown"] = { link = "markdownBlockquote" },
		["@markup.strong.markdown_inline"] = { link = "markdownBold" },
		["@markup.italic.markdown_inline"] = { link = "markdownItalic" },
		["@markup.heading.markdown"] = { link = "markdownBold" },
		["@markup.link.label.markdown_inline"] = { link = "markdownLinkText" },
		["@markup.strikethrough.markdown_inline"] = { strikethrough = true },

		-- Ruby
		rubyKeywordAsMethod = { fg = c.info, bold = true },
		rubyInterpolation = { fg = c.warning },
		rubyInterpolationDelimiter = { fg = c.warning },
		rubyStringDelimiter = { fg = c.success },
		rubyBlockParameterList = { fg = c.info },
		rubyDefine = { fg = c.error, italic = options.enable_italics },
		rubyModuleName = { fg = c.heading },
		rubyAccess = { fg = c.accent },
		rubyAttribute = { fg = c.warning },
		rubyMacro = { fg = c.error, italic = options.enable_italics },
		rubyBangPredicateMethod = { fg = c.heading },
		-- rubyModuleBlock = { fg = c.warning },
		-- rubyClassBlock = { fg = c.warning },
		-- rubyMethodBlock = { fg = c.warning },

		-- sh/zsh
		shRange = { fg = c.fg0 },
		shTestOpr = { fg = c.accent },
		shOption = { fg = c.info },
		bashStatement = { fg = c.accent },
		shOperator = { fg = c.accent },
		shQuote = { fg = c.success },
		shSet = { fg = c.accent },
		shSetList = { fg = c.info },
		shSnglCase = { fg = c.accent },
		shVariable = { fg = c.info },
		shVarAssign = { fg = c.accent },
		shCmdSubRegion = { fg = c.success },
		shCommandSub = { fg = c.accent },
		shFunctionOne = { fg = c.success, bold = true },
		shFunctionKey = { fg = c.error, italic = options.enable_italics },

		-- ZSH
		zshoptionstart = { fg = c.heading, italic = options.enable_italics },
		zshOption = { fg = c.info },
		zshSubst = { fg = c.warning },
		zshFunction = { fg = c.success, bold = true },
		zshDeref = { fg = c.info },
		zshTypes = { fg = c.accent },
		zshVariableDef = { fg = c.info },

		-- JSON
		jsonKeyword = { fg = c.error },
		-- jsonQuote = { fg = c.error },
		jsonBraces = { fg = c.fg0 },

		-- Java
		javaClassDecl = { fg = c.error, italic = options.enable_italics },
		javaMethodDecl = { fg = c.error, italic = options.enable_italics },
		javaVarArg = { fg = c.success },
		javaAnnotation = { fg = c.info },
		javaUserLabel = { fg = c.heading },
		javaContant = { fg = c.heading },
		javaTypedef = { fg = c.info },
		javaFold = { fg = c.heading },
		javaOperator = { fg = c.heading },
		javaParen = { fg = c.fg0 },
		javaParen1 = { fg = c.fg0 },
		javaParen2 = { fg = c.fg0 },
		javaParen3 = { fg = c.fg0 },
		javaParen4 = { fg = c.fg0 },
		javaParen5 = { fg = c.fg0 },

		--  vim
		vimLet = { fg = c.accent },
		vimFunction = { fg = c.success, bold = true },
		vimIsCommand = { fg = c.fg0 },
		vimUserFunc = { fg = c.success, bold = true },
		vimFuncName = { fg = c.success, bold = true },
		vimMap = { fg = c.heading, italic = options.enable_italics },
		vimNotation = { fg = c.info },
		vimMapLhs = { fg = c.success },
		vimMapRhs = { fg = c.success },
		vimSetEqual = { fg = c.warning },
		vimOption = { fg = c.info },
		vimUserAttrbKey = { fg = c.warning },
		vimUserAttrb = { fg = c.success },
		vimAutoCmdSfxList = { fg = c.info },
		vimSynType = { fg = c.accent },
		vimHiBang = { fg = c.accent },
		vimSet = { fg = c.warning },
		vimSetSep = { fg = c.mg1 },
		vimContinue = { fg = c.mg1 },

		--Make
		makeIdent = { fg = c.info },
		makeSpecTarget = { fg = c.warning },
		makeTarget = { fg = c.info },
		makeCommands = { fg = c.accent },

		-- Cmake
		cmakeCommand = { fg = c.accent },
		cmakeKWconfigure_package_config_file = { fg = c.warning },
		cmakeKWwrite_basic_package_version_file = { fg = c.warning },
		cmakeKWExternalProject = { fg = c.info },
		cmakeKWadd_compile_definitions = { fg = c.info },
		cmakeKWadd_compile_options = { fg = c.info },
		cmakeKWadd_custom_command = { fg = c.info },
		cmakeKWadd_custom_target = { fg = c.info },
		cmakeKWadd_definitions = { fg = c.info },
		cmakeKWadd_dependencies = { fg = c.info },
		cmakeKWadd_executable = { fg = c.info },
		cmakeKWadd_library = { fg = c.info },
		cmakeKWadd_link_options = { fg = c.info },
		cmakeKWadd_subdirectory = { fg = c.info },
		cmakeKWadd_test = { fg = c.info },
		cmakeKWbuild_command = { fg = c.info },
		cmakeKWcmake_host_system_information = { fg = c.info },
		cmakeKWcmake_minimum_required = { fg = c.info },
		cmakeKWcmake_parse_arguments = { fg = c.info },
		cmakeKWcmake_policy = { fg = c.info },
		cmakeKWconfigure_file = { fg = c.info },
		cmakeKWcreate_test_sourcelist = { fg = c.info },
		cmakeKWctest_build = { fg = c.info },
		cmakeKWctest_configure = { fg = c.info },
		cmakeKWctest_coverage = { fg = c.info },
		cmakeKWctest_memcheck = { fg = c.info },
		cmakeKWctest_run_script = { fg = c.info },
		cmakeKWctest_start = { fg = c.info },
		cmakeKWctest_submit = { fg = c.info },
		cmakeKWctest_test = { fg = c.info },
		cmakeKWctest_update = { fg = c.info },
		cmakeKWctest_upload = { fg = c.info },
		cmakeKWdefine_property = { fg = c.info },
		cmakeKWdoxygen_add_docs = { fg = c.info },
		cmakeKWenable_language = { fg = c.info },
		cmakeKWenable_testing = { fg = c.info },
		cmakeKWexec_program = { fg = c.info },
		cmakeKWexecute_process = { fg = c.info },
		cmakeKWexport = { fg = c.info },
		cmakeKWexport_library_dependencies = { fg = c.info },
		cmakeKWfile = { fg = c.info },
		cmakeKWfind_file = { fg = c.info },
		cmakeKWfind_library = { fg = c.info },
		cmakeKWfind_package = { fg = c.info },
		cmakeKWfind_path = { fg = c.info },
		cmakeKWfind_program = { fg = c.info },
		cmakeKWfltk_wrap_ui = { fg = c.info },
		cmakeKWforeach = { fg = c.info },
		cmakeKWfunction = { fg = c.info },
		cmakeKWget_cmake_property = { fg = c.info },
		cmakeKWget_directory_property = { fg = c.info },
		cmakeKWget_filename_component = { fg = c.info },
		cmakeKWget_property = { fg = c.info },
		cmakeKWget_source_file_property = { fg = c.info },
		cmakeKWget_target_property = { fg = c.info },
		cmakeKWget_test_property = { fg = c.info },
		cmakeKWif = { fg = c.info },
		cmakeKWinclude = { fg = c.info },
		cmakeKWinclude_directories = { fg = c.info },
		cmakeKWinclude_external_msproject = { fg = c.info },
		cmakeKWinclude_guard = { fg = c.info },
		cmakeKWinstall = { fg = c.info },
		cmakeKWinstall_files = { fg = c.info },
		cmakeKWinstall_programs = { fg = c.info },
		cmakeKWinstall_targets = { fg = c.info },
		cmakeKWlink_directories = { fg = c.info },
		cmakeKWlist = { fg = c.info },
		cmakeKWload_cache = { fg = c.info },
		cmakeKWload_command = { fg = c.info },
		cmakeKWmacro = { fg = c.info },
		cmakeKWmark_as_advanced = { fg = c.info },
		cmakeKWmath = { fg = c.info },
		cmakeKWmessage = { fg = c.info },
		cmakeKWoption = { fg = c.info },
		cmakeKWproject = { fg = c.info },
		cmakeKWqt_wrap_cpp = { fg = c.info },
		cmakeKWqt_wrap_ui = { fg = c.info },
		cmakeKWremove = { fg = c.info },
		cmakeKWseparate_arguments = { fg = c.info },
		cmakeKWset = { fg = c.info },
		cmakeKWset_directory_properties = { fg = c.info },
		cmakeKWset_property = { fg = c.info },
		cmakeKWset_source_files_properties = { fg = c.info },
		cmakeKWset_target_properties = { fg = c.info },
		cmakeKWset_tests_properties = { fg = c.info },
		cmakeKWsource_group = { fg = c.info },
		cmakeKWstring = { fg = c.info },
		cmakeKWsubdirs = { fg = c.info },
		cmakeKWtarget_compile_definitions = { fg = c.info },
		cmakeKWtarget_compile_features = { fg = c.info },
		cmakeKWtarget_compile_options = { fg = c.info },
		cmakeKWtarget_include_directories = { fg = c.info },
		cmakeKWtarget_link_directories = { fg = c.info },
		cmakeKWtarget_link_libraries = { fg = c.info },
		cmakeKWtarget_link_options = { fg = c.info },
		cmakeKWtarget_precompile_headers = { fg = c.info },
		cmakeKWtarget_sources = { fg = c.info },
		cmakeKWtry_compile = { fg = c.info },
		cmakeKWtry_run = { fg = c.info },
		cmakeKWunset = { fg = c.info },
		cmakeKWuse_mangled_mesa = { fg = c.info },
		cmakeKWvariable_requires = { fg = c.info },
		cmakeKWvariable_watch = { fg = c.info },
		cmakeKWwrite_file = { fg = c.info },

		-- Yaml
		namlKey = { fg = c.error },
		yamlConstant = { fg = c.heading },

		-- toml
		tomlKey = { fg = c.error },
		tomlBoolean = { fg = c.info },
		tomlTableArray = { link = "tomlTable" },
		["@property.toml"] = { fg = c.info },

		-- DOS
		dosiniLabel = { fg = c.heading },
		dosiniValue = { fg = c.fg0 },
		dosiniHeader = { fg = c.error },

		-- mini.hipatterns
		MiniHipatternsFixme = { bg = c.error, fg = c.bg0 },
		MiniHipatternsHack = { bg = c.warning, fg = c.bg0 },
		MiniHipatternsTodo = { bg = c.info, fg = c.bg0 },
		MiniHipatternsNote = { bg = c.success, fg = c.bg0 },

		-- Snacks.Dashboard
		SnacksDashboardTitle = { fg = c.dashboard },
		SnacksDashboardHeader = { fg = c.dashboard },
		SnacksDashboardFooter = { fg = c.dashboard },
		SnacksDashboardIcon = { fg = c.success },
		SnacksDashboardFile = { fg = c.fg0 },
		SnacksDashboardDesc = { fg = c.fg0 },
		SnacksDashboardKey = { fg = c.heading },
		SnacksDashboardSpecial = { fg = c.warning },

		-- Snacks.Picker
		SnacksPickerBoxTitle = { fg = c.success },
		SnacksPickerUndoAdded = { fg = c.success },
		SnacksPickerGitStatusAdded = { fg = c.success },
	}

	theme.defer = {}

	options.on_highlights(theme.highlights, theme.colors)

	return theme
end

return M
